/** QIMA web surface. Production modules remain intact; /demo is the DOC-11 prototype layer. */
import { Hono } from 'hono';
import { loadQimaConfig } from '@qima/config';
import type { QimaBindings } from '../../api/src/bindings';
import { QIMA_CURRENT_PHASE } from '../../api/src/phase';
import { renderActivityShell } from './activity-shell';
import { renderParticipantShell } from './participant-shell';
import { renderProgramShell } from './program-shell';
import { renderBootstrapShell } from './shell';
import { renderPrototypeShell } from './prototype-shell';
import { renderPrototypeAdminShell } from './prototype-admin-shell';
import { renderPrototypeAdminLoginShell } from './prototype-admin-login-shell';

export const web = new Hono<{ Bindings: QimaBindings }>();
web.get('/demo', (c) => c.html(renderPrototypeShell()));
web.get('/demo/admin/login', (c) => c.html(renderPrototypeAdminLoginShell()));
web.get('/demo/admin', (c) => c.html(renderPrototypeAdminShell()));
web.get('/programs', (c) => c.html(renderProgramShell({ mode: 'list' })));
web.get('/programs/new', (c) => c.html(renderProgramShell({ mode: 'create' })));
web.get('/programs/:programId/edit', (c) => c.html(renderProgramShell({ mode: 'edit', programId: c.req.param('programId') })));
web.get('/programs/:programId', (c) => c.html(renderProgramShell({ mode: 'detail', programId: c.req.param('programId') })));
web.get('/activities', (c) => c.html(renderActivityShell({ mode: 'list' })));
web.get('/activities/new', (c) => c.html(renderActivityShell({ mode: 'create' })));
web.get('/activities/:activityId/edit', (c) => c.html(renderActivityShell({ mode: 'edit', activityId: c.req.param('activityId') })));
web.get('/activities/:activityId', (c) => c.html(renderActivityShell({ mode: 'detail', activityId: c.req.param('activityId') })));
web.get('/participants', (c) => c.html(renderParticipantShell({ mode: 'list' })));
web.get('/participants/new', (c) => c.html(renderParticipantShell({ mode: 'create' })));
web.get('/participants/:participantId/edit', (c) => c.html(renderParticipantShell({ mode: 'edit', participantId: c.req.param('participantId') })));
web.get('/participants/:participantId', (c) => c.html(renderParticipantShell({ mode: 'detail', participantId: c.req.param('participantId') })));
web.get('/', (c) => { const config = loadQimaConfig(c.env as unknown as Record<string, string | undefined>); return c.html(renderBootstrapShell({ environment: config.appEnv, apiBasePath: config.apiBasePath, phase: QIMA_CURRENT_PHASE })); });