export function renderPrototypeShell(): string {
  return `<!doctype html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QIMA — Platform Pendidikan Al-Qur'an</title><link rel="stylesheet" href="/static/prototype.css"><link rel="stylesheet" href="/static/prototype-flow.css"></head><body>
<div class="prototype-app">
<header class="site-header"><a class="logo" href="#home"><span class="logo-mark">ق</span>QIMA</a><nav><a href="#programs">Program</a><a href="#activities">Aktivitas</a><a href="#about">Tentang</a><a href="#contact">Kontak</a></nav><div class="header-actions"><button class="unit-pill" id="unit-switcher"><span class="live-dot"></span><span id="unit-label">RQ Blumbang</span>⌄</button><a class="btn btn-primary btn-small" href="#register">Daftar</a></div><button class="menu-button" id="menu-button">☰</button></header>
<main>
<section class="hero" id="home"><div class="hero-glow glow-one"></div><div class="hero-glow glow-two"></div><div class="hero-copy reveal"><span class="eyebrow">✦ Platform Pendidikan Al-Qur'an</span><h1>Menumbuhkan generasi<br><em>dekat dengan Al-Qur'an.</em></h1><p class="hero-text">Ruang belajar yang hangat, terarah, dan bertumbuh bersama — untuk setiap unit pendidikan Al-Qur'an.</p><div class="hero-actions"><a class="btn btn-primary" href="#programs">Jelajahi Program →</a><a class="text-link" href="#about">Kenali QIMA ↗</a></div><div class="hero-proof"><div class="avatar-stack"><span>F</span><span>A</span><span>N</span><span>+</span></div><span><strong>500+</strong> peserta belajar<br><small>di unit yang terus bertumbuh</small></span></div></div><div class="hero-visual reveal"><div class="hero-card"><div class="card-top"><span class="mini-brand">RQ</span><span class="status-chip">● Aktif</span></div><div class="hero-illustration"><div class="arch"></div><div class="book">✦</div><div class="leaf leaf-a">◜</div><div class="leaf leaf-b">◝</div></div><div class="hero-card-bottom"><div><small>UNIT SAAT INI</small><strong id="hero-unit">Rumah Qur'an Blumbang</strong></div><span class="arrow-circle">→</span></div></div><div class="floating-card float-top"><span>✦</span><div><small>Program aktif</small><strong>8 program</strong></div></div><div class="floating-card float-bottom"><span>✓</span><div><small>Pendaftaran</small><strong>Terbuka hari ini</strong></div></div></div></section>
<section class="trust-strip"><strong>Satu platform.</strong><span>Banyak unit pendidikan Al-Qur'an.</span><div><span>RUMAH QUR'AN</span><span>PONDOK</span><span>LEMBAGA</span><span>KOMUNITAS</span></div></section>
<section class="section" id="programs"><div class="section-heading"><div><span class="eyebrow">Belajar & Bertumbuh</span><h2>Program pilihan untuk setiap perjalanan.</h2></div><a class="text-link" href="#programs">Lihat semua →</a></div><div class="program-grid" id="program-grid"></div></section>
<section class="section" id="activities"><div class="section-heading"><div><span class="eyebrow">Kegiatan Terdekat</span><h2>Selalu ada ruang untuk hadir bersama.</h2></div></div><div class="activity-layout"><div class="activity-feature"><div class="activity-date"><strong>18</strong><span>SEP<br>2026</span></div><div><span class="tag">Kegiatan Unit</span><h3>Khataman & Silaturahmi Santri</h3><p>Jumat, 16.00 WIB · Masjid Al-Ikhlas Blumbang</p><button class="ghost-button" data-toast="Detail kegiatan dibuka">Lihat detail →</button></div></div><div class="activity-list"><div class="activity-row"><span>24<br><small>SEP</small></span><div><strong>Kelas Tahsin Pekanan</strong><small>19.30 WIB · RQ Blumbang</small></div><span>→</span></div><div class="activity-row"><span>01<br><small>OKT</small></span><div><strong>Parenting Qur'ani</strong><small>09.00 WIB · Aula Unit</small></div><span>→</span></div><div class="activity-row"><span>10<br><small>OKT</small></span><div><strong>Wisuda Tahfidz</strong><small>08.00 WIB · Lapangan Utama</small></div><span>→</span></div></div></div></section>
<section class="section" id="about"><div class="about-card"><div class="about-visual"><div class="about-orb">ق</div></div><div class="about-copy"><span class="eyebrow">Tentang QIMA</span><h2>Satu fondasi untuk banyak kebaikan.</h2><p>QIMA membantu organisasi pendidikan Al-Qur'an mengelola program, aktivitas, peserta, pendaftaran, dan pengalaman digital dalam satu platform yang siap bertumbuh.</p><div class="feature-points"><span>✓ Identitas unit tetap unik</span><span>✓ Data terorganisir</span><span>✓ Siap multi-unit</span><span>✓ Pengalaman sederhana</span></div></div></div></section>
<section class="cta-section" id="register"><div><span class="eyebrow light">Mulai perjalananmu</span><h2>Temukan program yang tepat<br>untuk langkah berikutnya.</h2><p>Pilih program, isi pendaftaran, dan mulai belajar bersama komunitas.</p><button class="btn btn-light" id="register-button">Mulai Pendaftaran →</button></div></section>
<section class="section contact-section" id="contact"><div><span class="eyebrow">Hubungi Unit</span><h2>Ingin tahu lebih banyak?</h2><p>Tim RQ Blumbang siap membantu informasi program dan pendaftaran.</p></div><div class="contact-card"><strong>Rumah Qur'an Blumbang</strong><span>Blumbang · Banyumas, Jawa Tengah</span><span>Senin–Sabtu · 08.00–17.00 WIB</span><button class="ghost-button" data-toast="Kontak demo — WhatsApp terhubung saat production">Hubungi unit →</button></div></section>
</main><footer class="site-footer"><a class="logo" href="#home"><span class="logo-mark">ق</span>QIMA</a><p>One platform. Multiple independent units.</p><span>© 2026 QIMA Prototype</span></footer></div>
<div class="modal-backdrop" id="unit-modal" hidden><div class="modal" role="dialog" aria-modal="true"><button class="modal-close" id="unit-close">×</button><span class="eyebrow">Demo Unit Context</span><h2>Pilih identitas unit</h2><p>Shared core melayani identitas berbeda tanpa fork kode.</p><button class="unit-option active" data-unit="rq"><b>RQ</b><span><strong>Rumah Qur'an Blumbang</strong><small>Reference unit · Aktif</small></span>✓</button><button class="unit-option" data-unit="qima"><b>Q</b><span><strong>QIMA Platform</strong><small>Platform identity · Demo</small></span>○</button></div></div>
<div class="demo-flow-modal" id="demo-flow" hidden><div class="demo-flow-card" role="dialog" aria-modal="true"><button class="modal-close" id="flow-close">×</button><div class="demo-progress"><span class="done">01 Public</span><span id="flow-step-register">02 Registration</span><span>03 Admin</span></div><div id="flow-content"></div></div></div><div class="toast" id="toast"></div><script src="/static/prototype.js"></script></body></html>`;
}
