-- QIMA — Phase 2 (Authentication & Access) migration 0004
-- Task: T2.02 Session management — persistence schema.
--
-- Traceability:
-- - doc 10 §24 PHASE 2 — AUTHENTICATION & ACCESS (T2.02 Session management).
-- - doc 06 §42 API Security Contract: "Token/session expiration".
-- - doc 06 §39 ID Policy (UUID), §40 Timestamp Policy (UTC ISO-8601),
--   §41 Database Index Policy.
-- - doc 05 §23 Authentication: the provider is replaceable, so the session
--   record stores no provider-specific payload.
-- - .codex/IMPLEMENTATION_RULES.md §7 Data Rule: additive and non-destructive.
--
-- Non-destructive and additive: no DROP, no data transformation, and no change
-- to any Phase 1 table.
--
-- Portability note: D1 is SQLite. UUID -> TEXT, TIMESTAMP -> TEXT (ISO-8601
-- UTC), BOOLEAN -> INTEGER 0/1.

-- ---------------------------------------------------------------------------
-- T2.02 — sessions (doc 06 §42 "Token/session expiration")
--
-- SECURITY DESIGN — why only a hash of the token is stored:
--
-- The session token is a bearer credential: whoever holds it IS the user. If
-- the raw token were stored, a single leaked database backup or a successful
-- read-only SQL injection would hand an attacker live sessions for every
-- signed-in user. Storing only a SHA-256 hash means the table cannot be
-- replayed: the raw token exists solely in the client's possession and in the
-- memory of the request that issued it.
--
-- SHA-256 without a salt is deliberate and is NOT the password case: a session
-- token is 256 bits of cryptographic randomness generated by the server, so it
-- has no dictionary to attack and needs no key-stretching. Stretching here
-- would only add CPU cost to every authenticated request.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  -- Hex-encoded SHA-256 of the raw session token (64 characters).
  token_hash TEXT NOT NULL,
  -- Absolute expiry. Enforced by the application on every read AND kept here
  -- so an expired session is identifiable without application context.
  expires_at TEXT NOT NULL,
  -- Set when the session is explicitly ended (logout, T2.04). The row is kept
  -- rather than deleted so the audit trail can distinguish "logged out" from
  -- "never existed".
  revoked_at TEXT,
  -- Request provenance, recorded for session-security review (doc 09 §38).
  ip_address TEXT,
  user_agent TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  last_used_at TEXT,
  CONSTRAINT sessions_user_fk FOREIGN KEY (user_id)
    REFERENCES users (id) ON DELETE CASCADE,
  -- A token hash identifies exactly one session. UNIQUE also makes a hash
  -- collision or a duplicated insert a hard failure instead of an ambiguous
  -- lookup that could authenticate the wrong user.
  CONSTRAINT sessions_token_hash_unique UNIQUE (token_hash),
  -- Shape of a hex SHA-256 digest, enforced in the database so no writer can
  -- store a raw token in this column by mistake.
  CONSTRAINT sessions_token_hash_format CHECK (
    length(token_hash) = 64 AND token_hash NOT GLOB '*[^0-9a-f]*'
  ),
  -- A session that expires at or before its creation instant is never valid;
  -- rejecting it at write time prevents a silently dead session.
  CONSTRAINT sessions_expiry_after_creation CHECK (expires_at > created_at)
);

-- doc 06 §41 index policy.
--
-- The token-hash lookup runs on EVERY authenticated request, so it must be an
-- index scan; the UNIQUE constraint already provides one, and the explicit
-- index below keeps the required-index contract self-describing.
CREATE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions (token_hash);
-- Listing or revoking every session of a user (logout-everywhere, account
-- suspension) filters by user_id.
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions (user_id);
-- Expiry sweeps and "active sessions" reads filter by expires_at.
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions (expires_at);

-- ---------------------------------------------------------------------------
-- Immutability guard.
--
-- A session's identity (which user it belongs to, and which token unlocks it)
-- must never change after issuance. Allowing an UPDATE of `user_id` or
-- `token_hash` would permit privilege escalation by rewriting an existing
-- session onto another account instead of authenticating as them.
--
-- Mutable by design: `revoked_at` (logout) and `last_used_at` (activity
-- tracking). The trigger is scoped `BEFORE UPDATE OF <columns>` so those
-- legitimate writes are unaffected.
-- ---------------------------------------------------------------------------
CREATE TRIGGER IF NOT EXISTS sessions_identity_is_immutable
BEFORE UPDATE OF user_id, token_hash, created_at ON sessions
BEGIN
  SELECT RAISE(ABORT, 'sessions.user_id, token_hash and created_at are immutable');
END;
